Realtime Video Routing
flyinghead/flycast pull request #1126
Opened 2023-06-25 05:23 UTC by vkedwardli

## Motivation

<details>
  <summary>Currently there are near 30 live streamers for Gundam DX:</summary>

[Ken Ling Sing](https://youtube.com/channel/UCdY5Ip-JJNNuRdBxjzHNGMg)
[Yip Philos](https://youtube.com/channel/UCX4BckWkRhgS0EVgHkh2yCQ)
[老虎仔高達日常](https://youtube.com/channel/UCE_oasD2udLDIXvJK5ptcIQ)
[雞坤的遊戲日常](https://youtube.com/channel/UCEzRGrMR_ZTRW271enMFNnQ)
[飛龍補習社 - 飛龍高達日常 GDX vs ZDX](https://youtube.com/channel/UCcHizzTrohCVsdBPkauW5cw)
[藍魔](https://youtube.com/channel/UCUMPTJ6U53fW-AYgszdeiLA)
[とる。](https://youtube.com/channel/UCt5kM1350roABgSBXq4WBCA)
[連ジZネット対戦](https://youtube.com/channel/UCmH_v-7wWITjlx9rLk3BJmA)
[くまたんご](https://youtube.com/channel/UCk7QS8tmsRVpK_EUOS8obpg)
[360 nanasu](https://youtube.com/channel/UCkKv7Bv0pE_ODRcAwd7ATGw)
[KZのゲーム部屋](https://youtube.com/channel/UCLzJAKOAijSN08i_025g2cQ)
[KT Livestream - 機動戦士ガンダム 連邦VS.ジオンDX Gundam DX ](https://youtube.com/channel/UCEUDyhjJfMdo247nkpr20ow)  
[Dx賤骨頭](https://youtube.com/channel/UC4eAqzZpKPVvRhSv8Ly2VIQ)
[CivicHo](https://youtube.com/channel/UCrA2oZVUQtSiNuJyUm2QuVQ)
[ブランクリン](https://youtube.com/channel/UCrzBGYiKdYav25fEpzvNLEQ)
[ken ken](https://youtube.com/channel/UCBmIKqfBUj5qdzST0_1w5bA)
[otusokumaru](https://youtube.com/channel/UCKvlRKHiTlvNHtSPyXNfRXg)
[Tung Tung](https://youtube.com/channel/UCzTmiJyb8VKDdbR5drhR4yQ)
[MayaShiki](https://youtube.com/channel/UCmPJX9VTe5xze29fmKyN1tQ)
[ng6ng6](https://youtube.com/channel/UCGEU6992zb3EX-rD0mpTguA)
[BADASS ACADEMY](https://youtube.com/channel/UCxFI51r4U-VX43uuS7ZTeSA)
[HeartMan](https://youtube.com/channel/UCNi0dWUlseiUZHvFlTudNtA)
[Law B](https://youtube.com/channel/UCDuKhd1A00WssETE1Yuys-w)
[馬高珍藏小館觀塘玩具店](https://youtube.com/channel/UCarkz3sAX_aj4H_uONqQO-g)
[跟機](https://youtube.com/channel/UCCNBplqJ8VZMoc8a8rL59yQ)
[FREE Channel](https://youtube.com/channel/UCEyqcKffqe-jrZs9oFGKSmA)
[さんじゅうに](https://youtube.com/channel/UCbs4zvYaa0JpxzIo6Fa0NqA)

</details>

However the traditional way of Desktop Capture / Windows Capture is **very CPU intensive**.

The streamer's computer may not be powerful enough to handle game play + capture + live streaming,  for example [this live stream video](https://www.youtube.com/live/Cz5FNEHfybM?feature=share&t=221) shows that it is quite laggy when using Window Capture.
And [this player](https://youtu.be/Kbjy4GN4klg?t=555) can't even live stream, so he uploads a 360p recording after match instead.

The performance issue with Desktop Capture / Windows Capture is particularly serious with Retina / HiDPI monitor. 

So instead of relying on CPU, we could share the GPU texture directly by using [Syphon](https://syphon.github.io/) (macOS) or [Spout](https://leadedge.github.io/) (Windows)
Both libraries are the golden standard in the AV industry, with the following features:
- Hardware accelerated surface sharing on the GPU
- Zero latency
- Zero copy

By routing the texture directly to OBS, the same user is able to have a smooth live stream now: https://www.youtube.com/live/GqapMPY4teE?feature=share&t=69

## Implementation

![image](https://github.com/flyinghead/flycast/assets/602245/12ef9cc3-0f2d-446d-90db-916bd4e3a2fa)
<img width="901" alt="image" src="https://github.com/flyinghead/flycast/assets/602245/292ffb22-f993-4a0d-9610-73a53fdef039">
<img width="659" alt="image" src="https://github.com/flyinghead/flycast/assets/602245/cad73fc4-c542-4425-8414-c25bb4d35bf6">

For Retina / HiDPI monitor users, the `Scale down before sending` could be useful for reducing GPU burden by scaling the shared texture to the match with their streaming resolution.

Supported platforms & graphic backends:

- Windows, 64-bit (MSVC + MinGW) + 32-bit !?
   - OpenGL
   - DirectX 11
- macOS, Universal
   - OpenGL
   - Vulkan (Metal)

Supported video settings:
- Widescreen / Super Widescreen
- Render to Texture
- Full Framebuffer Emulation
- Overlay (e.g. In-game VMU, FPS, GGPO Stats)
- Resize window / Resize sharing texture / Change renderer without restarting

By design, nothing will be shared when Settings / Menu is opened, only the video content + Overlay are shared.
For users who do not need to share any overlay, it is technically possible to share the internal Dreamcast video texture (same resolution as your `Internal Resolution` setting) directly, I cannot see any use case at this moment so this option is not implemented.

## Side-effects
- A new compiler definition to target macOS `TARGET_MAC`
- `VK_USE_PLATFORM_METAL_EXT` is enabled
- Fix Xcode pretty print log

## Usage
For macOS OBS, Syphon is built in
<img width="200" alt="image" src="https://github.com/flyinghead/flycast/assets/602245/af3854d9-92a5-404d-b5d0-ccec4d9bfa6e">

For Windows OBS, user can install the [Spout2 Plugin for OBS Studio](https://github.com/Off-World-Live/obs-spout2-plugin/releases)
<img alt="image" src="https://docs.offworld.live/obs-spout-plugin/images/spoutsource.jpg">

You could even route multiple Flycast textures, skew/distort the quads to mimic surround display!?
![image](https://github.com/flyinghead/flycast/assets/602245/b0a9dcbc-d9e4-4b0e-aeaa-e6103aa95a30)

Or a multi-projection setup equivalent to 800" ultrawide screen!?
<img width="736" alt="image" src="https://github.com/flyinghead/flycast/assets/602245/849905c1-7cc9-4029-bfa6-c86a01c85db6">

2023-06-25 06:08 UTC, vade commented
Ha dope.

2023-06-25 13:24 UTC, flyinghead commented
Some general questions:
Why not implementing video routing in per-pixel renderers?

Any solution for the linux world?

2023-06-25 13:43 UTC, flyinghead requested changes

2023-06-25 13:43 UTC, flyinghead commented on core/rend/dx11/dx11_renderer.cpp
> +#endif
no need for #ifdef here. It's not a problem if these objects are defined and reset in all builds.

2023-06-25 13:43 UTC, flyinghead commented on core/rend/dx11/dx11_renderer.cpp
> +
I'd rather have an empty implementation if `VIDEO_ROUTING` is not defined to avoid #ifdef all over the place

2023-06-25 13:43 UTC, flyinghead commented on core/rend/dx11/dx11context.cpp
> +
empty implementation preferred over #ifdef

2023-06-25 13:43 UTC, flyinghead commented on core/rend/gles/gles.cpp
> +#endif
avoid #ifdef

2023-06-25 13:43 UTC, flyinghead commented on core/rend/gles/gles.h
> +
avoid #ifdef

2023-06-25 13:43 UTC, flyinghead commented on core/rend/dx11/dx11_renderer.cpp
> +		pTexture->Release();
you release both `pResource` and `pTexture` interface pointers and use `pTexture` afterwards. Unless I'm missing something you should only call Release after you're done using the object

2023-06-25 13:48 UTC, vkedwardli commented
I haven't take a look at the OIT renderers (Oh they are separate classes?), but it's working in macOS's Vulkan Per Pixel + Windows DX11's Per Pixel directly from my testing.

I have quickly search for Linux solution before, but I don't see any popular library available out there

As @vade have previously [mention this before](http://blog.jackphelan.xyz/syphon-for-linux-the-missing-link):
> Linux requires a collaborative effort between the kernel developers and the hardware /GPU driver teams, and an agreed upon API to access GPU memory across process boundaries.
> 
> Apple was able to do that via IOSurface for us. I believe that it required specific collaboration with Nvidia, intel, ATI, Imgtec, and other GPU vendors in Apples ecosystem to ensure it works.
> 
> I don’t believe linux/the community has this capability, or a need / desire for it.


But I do notice there is a library named [PipeWire](https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master), which OBS Studio is using it as [Window Capture](https://github.com/obsproject/obs-studio/blob/ba92140f2b68b1a7215819f2ef65c166ffc8b372/plugins/linux-pipewire/screencast-portal.c#L668), but not as a video route solution?


Relevant links:

- [Inter-Process Texture Sharing with DMA-BUF](https://blaztinn.gitlab.io/post/dmabuf-texture-sharing/)
- [PipeWire DMA-BUF](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/doc/dma-buf.dox)

2023-06-25 14:22 UTC, flyinghead commented
I'm surprised that the DX11 per-pixel renderer works because it overrides the `Render()` method so `RenderVideoRouting()` isn't called. Same for OpenGL.
It probably works in some cases (Full Framebuffer Emulation or direct framebuffer rendering) since they use a different code path. Vulkan should work for both since you grab the frame directly from the swap chain framebuffer.

2023-06-25 14:27 UTC, flyinghead commented on core/rend/dx11/dx11_renderer.cpp
> +			backBufferTexture = pTexture;
Same reference counting issue here: you keep a (static!) reference to `pTexture` via `backbufferTexture` after calling Release.
Do you really need a static variable here?
If not move the move the `pTexture->Release()` to the end of the variable scope.
If yes you need to call `Release()` on it when assigning a new reference.

2023-06-25 15:34 UTC, vkedwardli commented
> I'm surprised that the DX11 per-pixel renderer works
I guess it is my virtualized ARM Windows bug, enabled both OpenGL OIT and DX11 OIT now

Empty method are provided for `initVideoRouting()` and `RenderVideoRouting()`.
All video routing related call for OpenGL/DX11/Vulkan(Metal) are relocated in `RenderVideoRouting()`.

2023-06-25 18:00 UTC, vkedwardli commented
Before [PipeWire-based Camera](https://github.com/obsproject/obs-studio/pull/5728) is implemented, Linux users should be able to use https://github.com/nowrep/obs-vkcapture (using `VK_EXT_external_memory_dma_buf`) to have the same zero-copy performance.

2023-06-25 18:39 UTC, flyinghead requested changes

2023-06-25 18:39 UTC, flyinghead commented on core/hw/pvr/Renderer_if.h
> +	virtual void RenderVideoRouting() {}
This is an internal method of renderers so I don't think it should be defined in this generic interface. I'd rather have empty, non-virtual implementations in each renderer that needs it:
```c++
void OpenGLRenderer::RenderVideoRouting()
{
#ifdef VIDEO_ROUTING
    // implementation...
#endif
}
```

2023-06-26 09:56 UTC, merged

2023-06-26 14:50 UTC, vkedwardli commented
Thank you so much for taking the time to review and accept this!

2023-09-06 19:08 UTC, vkedwardli commented
> And [this player](https://youtu.be/Kbjy4GN4klg?t=555) can't even live stream, so he uploads a 360p recording after match instead.

It is verified that with Spout2 capture, he can run a [720p live stream](https://www.youtube.com/watch?v=A73XYn-SgOs) smoothly now. Fullscreen gameplay with disabled Multi-threaded emulation!
(Although we decided to downgrade to 480p to ensure 0 lag gameplay)

Another player with heavy texture replacement also confirmed that, he is able to live stream with fullscreen + internal 2x resolution now (he could only play in a half sized window + 1.5x resolution before)