Multiple save states
flyinghead/flycast pull request #248
Opened 2021-05-22 13:04 UTC by ktyshmt

Resolve https://github.com/flyinghead/flycast/issues/156 

This change allows you to save multiple states.
I built it with appveyor and confirmed that it works on Windows 10.

| After clicking Load State | After clicking Save State |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/36216063/119227454-e7725000-bb48-11eb-873e-e1305fbb108e.png) | ![image](https://user-images.githubusercontent.com/36216063/119227468-f953f300-bb48-11eb-9702-f160ccfb64ae.png) |

I don't usually write C ++ and don't speak English, so there may be some things to fix. Please let me know if there is something wrong.

I would be grateful if you could merge it. Thank you!

2021-05-24 08:52 UTC, flyinghead requested changes
Thank you for your contribution. I added a couple of comments but overall the implementation is fine.

However the UI is ... perfectible. I don't really like presenting columns of buttons like this to the user. A system of slots (10) would be preferable: the user can choose which slot is the current one, and save/load state uses the current slot to save or load.

2021-05-24 08:52 UTC, flyinghead commented on core/emulator.h
> +void dc_savestate(int index);
I'm surprised the compiler isn't complaining about this redefinition. Anyway this line isn't necessary.

2021-05-24 08:52 UTC, flyinghead commented on core/emulator.h
> +void dc_loadstate(int index);
Same remark as above

2021-05-24 08:52 UTC, flyinghead commented on core/rend/gui.cpp
> +				gui_state = GuiState::Closed;
This line isn't necessary since `gui_state` is already assigned at line 1950.

2021-05-24 08:52 UTC, flyinghead commented on core/rend/gui.cpp
> +				gui_state = GuiState::Closed;
Same remark as above.

2021-05-24 08:52 UTC, flyinghead commented on core/rend/gui.cpp
> +	if (ImGui::Button(saving ? "Stop Saving" : "Stop Loading", ImVec2(150 * scaling, 50 * scaling)))
I would simply name this button "Cancel" instead of Stop Saving/Loading.
And centering the button horizontally would be nice too.

2021-05-24 16:50 UTC, ktyshmt commented
Thank you very much for your review! Sorry for taking your time due to my elementary mistakes. I pushed those fix commits. 

![image](https://user-images.githubusercontent.com/36216063/119379441-74a8d680-bcfa-11eb-93a3-6cd558eda0dc.png)

> A system of slots (10) would be preferable: the user can choose which slot is the current one, and save/load state uses the current slot to save or load.

Certainly. With the addition of this feature, users will have one more annoying click to save and load. I used SSF (Sega Saturn emulator)s function as a reference without thinking about anything.
I think A system of slots is preferable for existing users. But it seems difficult for me to implement it. sorry...
If 'perfectible' is a euphemism and means it can't be merged as it is, I'm going to close this pull request. (I don't understand the fine nuances)

The reason I needed this feature was not because I wanted to save multiple game progresses, but because I was save a lot of game turning points.
I think most games have a save function originally. What's missing is the ability to save before and after small choices and load as needed.
I only thought about adding this feature to switch data frequently in a short period of time, so I made it this way.
If it is a function to save the progress, I think it would be nice to be able to set the file name. Because it is difficult to determine what kind of data it is with just the number.

I'm wondering if it's translated into English well, so if you don't understand it, you can ignore it. I am completely grateful to you. If there are any negative expressions in my writing, it's just a matter of language ability and I hope you don't mind.

2021-05-26 15:36 UTC, flyinghead approved these changes

2021-05-28 12:57 UTC, flyinghead commented
No problem. I will merge it but I need to figure out the UI first.

2021-06-03 11:22 UTC, merged